import { describe, expect, it } from "vitest";
import { createEmptyPortfolioDraft, validatePortfolioDraft } from "../shared/portfolio";
import { applyPortfolioComposition, composeRequestSchema, portfolioComposeInput } from "../shared/portfolioCompose";

function original(){return {...createEmptyPortfolioDraft(),name:"Jordan",headline:"Graphic designer",email:"jordan@example.com",location:"Brooklyn",links:[{id:"linkedin",label:"Profile",url:"https://example.com/jordan"}],projects:[{id:"class-project",title:"Class project",summary:"A poster for class",role:"Student designer",process:"Tested type choices",outcome:"Learned to simplify",link:"https://example.com/project"}]};}
describe("Conversational portfolio design",()=>{
 it("sends only content and controlled design choices, not contact or links",()=>{const input=portfolioComposeInput(original());expect(JSON.stringify(input)).not.toContain("jordan@example.com");expect(input).not.toHaveProperty("location");expect(input).not.toHaveProperty("links");expect(input.projects[0]).not.toHaveProperty("link");expect(input.template).toBe("editorial");});
 it("keeps contact details and original project links when applying changes",()=>{const base=original();const next=applyPortfolioComposition(base,{...portfolioComposeInput(base),headline:"Design with a clear point of view",template:"studio",accent:"rose"});expect(next.email).toBe(base.email);expect(next.links).toEqual(base.links);expect(next.projects[0].link).toBe(base.projects[0].link);expect(next.template).toBe("studio");});
 it("preserves incomplete contact text in the editor without making it an active link",()=>{const base={...original(),email:"jordan@"};const next=applyPortfolioComposition(base,portfolioComposeInput(base));expect(next.email).toBe("jordan@");expect(()=>validatePortfolioDraft(next)).toThrow();});
 it("can add a described project without copying contact data into it",()=>{const base=original();const content=portfolioComposeInput(base);content.projects.push({id:"new-class-project",title:"Logo study",summary:"A second class project",role:"",process:"",outcome:""});const next=applyPortfolioComposition(base,content);expect(next.projects).toHaveLength(2);expect(next.projects[1].link).toBeUndefined();expect(next.id).toBe(base.id);});
 it("rejects repeated project IDs",()=>{const base=original();const content=portfolioComposeInput(base);content.projects.push(content.projects[0]);expect(()=>applyPortfolioComposition(base,content)).toThrow(/repeated/);});
 it("rejects arbitrary template or injected execution fields",()=>{const base=original();expect(()=>applyPortfolioComposition(base,{...portfolioComposeInput(base),template:"custom-script"})).toThrow();expect(()=>applyPortfolioComposition(base,{...portfolioComposeInput(base),html:"<script>alert(1)</script>"})).toThrow();});
 it("rejects over-limit content before it can replace the draft",()=>{const base=original();expect(()=>applyPortfolioComposition(base,{...portfolioComposeInput(base),headline:"x".repeat(181)})).toThrow();expect(base.headline).toBe("Graphic designer");});
 it("bounds the user's request and does not accept extra client permissions",()=>{const body={instruction:"Please use a warmer look",draft:portfolioComposeInput(original())};expect(composeRequestSchema.safeParse(body).success).toBe(true);expect(composeRequestSchema.safeParse({...body,instruction:"x".repeat(3001)}).success).toBe(false);expect(composeRequestSchema.safeParse({...body,pro:true}).success).toBe(false);});
});
